### Практическое задание Часть 6

In [ ]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__Решение__

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

В итоге после преобразований мы получили матрицу треугльного вида, которая представляет следующую систему:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~~-2x_{3}+3x_{4}=4.
\end{cases}$$

Бесконечное множество решений принято записывать в виде _общего решения_.

Последнее уравнение содержит две неизвестных. Неизвестные, «сидящие» на ступеньках матрицы, принято назывть _базисными_, и их нужно выразить через _свободные_ неизвестные. В данном случае можно рассматривать в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=3c/2-2,$$
$$-x_{2}+3c/2-2+5c=-2 \; \Leftrightarrow \; x_{2}=13c/2,$$
$$x_{1} + 13c/2 - 3c/2+2 - 2c=0 \; \Leftrightarrow \; x_{1}=3c-2.$$

Таковым будет _общее решение системы_. Подставляя произвольные числа вместо $c$, мы получим _частное решение_. Например, при $c=0$:

$$x_{1}=-2,$$
$$x_{2}=0,$$
$$x_{3}=-2$$
$$x_{4}=0.$$

Считаем, что параметр $c$ может принимать бесконечное количество значений, при которых уравнения в системе будут обращаться в тождества.

Но, подставив общее решение в исходную систему, получим тождества __только при с=0__:

$$\begin{cases}
3c-2 + 13c/2 - 3c/2+2 -2с=0 \; \Leftrightarrow \; 6с=0 \; \Rightarrow \;c=0, \\
2(3c-2)+13c/2-3c/2+2+c=-2 \; \Leftrightarrow \; 12с-2=-2 \; \Rightarrow \;c=0, \\
3c-2+13c/2-3(3c/2-2)+c=4 \; \Leftrightarrow \; 6с+4=4 \; \Rightarrow \;c=0.
\end{cases}$$

Таким образом, либо я решил задачу неправильно, либо имеем только одно решение:

$$x_{1}=-2,$$
$$x_{2}=0,$$
$$x_{3}=-2$$
$$x_{4}=0.$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение__

__Согласно теореме Кронекера — Капелли__

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$

$$rank A=rank \tilde A.$$

Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.

In [ ]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
ar = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(ar)

print(f'Ранг матрицы a: {r}')
print(f'Ранг матрицы ar: {rr}')
print(f'Число неизвестных: 3')

Ранг матрицы a: 3
Ранг матрицы ar: 3
Число неизвестных: 3


In [ ]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
ar = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(ar)

print(f'Ранг матрицы a: {r}')
print(f'Ранг матрицы ar: {rr}')
print(f'Число неизвестных: 3')

Ранг матрицы a: 1
Ранг матрицы ar: 2
Число неизвестных: 3


In [ ]:
a = np.array([[1, 2, 5], [3, 1, -8]])
ar = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(ar)

print(f'Ранг матрицы a: {r}')
print(f'Ранг матрицы ar: {rr}')
print(f'Число неизвестных: 3')

Ранг матрицы a: 2
Ранг матрицы ar: 2
Число неизвестных: 3


__Ответ:__

а) система определена, т. е. имеет единственное решение

б) система несовместна

в) система совместна и имеет бесконечное количество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [ ]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
ar = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(ar)

print(f'Ранг матрицы a: {r}')
print(f'Ранг матрицы ar: {rr}')
print(f'Число неизвестных: 4')

Ранг матрицы a: 4
Ранг матрицы ar: 4
Число неизвестных: 4


__Ответ:__

Система определена, т. е. имеет единственное решение

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__

Система несовместна, если $rankA<rank \tilde A$

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar = np.array([[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]])

r = np.linalg.matrix_rank(a)
rr = np.linalg.matrix_rank(ar)

print(f'Ранг матрицы a: {r}')
print(f'Ранг матрицы ar: {rr}')

Ранг матрицы a: 2
Ранг матрицы ar: 2


$rankA=2$, так как первая строка это разница между удвоенной второй строкой и третьей, а значит первую строку можно отбросить.

Таким образом, чтобы $rank \tilde A$ был также равен двум, должно сохраняться условие: $a=2b-c$

а значит система является несовместной при условии, когда $a \neq 2b - c$


### Практическое задание Часть 7

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__Решение__

Для системы с $n$ уравнениями и $n$ неизвестными, если система уравнений невырождена (то есть $detA\neq 0$), то система определена, то есть имеет единственное решение, и это решение может быть найдено по формулам Крамера:

$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.

_Следует помнить, что правило Крамера применимо только к системам, в которых количество уравнений совпадает с количеством неизвестных._

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдем определитель матрицы коэффициентов:

In [ ]:
a = np.array([[1, -2], [3, -4]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 1 -2]
 [ 3 -4]]
Определитель:
2


$$detA=2\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$:

In [ ]:
a1 = np.array([[1, -2], [7, -4]])
print(f'Матрица:\n{a1}')
print(f'Определитель:\n{np.linalg.det(a1):.0f}')

Матрица:
[[ 1 -2]
 [ 7 -4]]
Определитель:
10


In [ ]:
a2 = np.array([[1, 1], [3, 7]])
print(f'Матрица:\n{a2}')
print(f'Определитель:\n{np.linalg.det(a2):.0f}')

Матрица:
[[1 1]
 [3 7]]
Определитель:
4


$$detA_{1}=10,$$

$$detA_{2}=4,$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2.$$


б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Найдем определитель матрицы коэффициентов:

In [ ]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


$$detA=43\neq 0,$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

In [ ]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица:\n{a1}')
print(f'Определитель:\n{np.linalg.det(a1):.0f}')

Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель:
86


In [ ]:
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица:\n{a2}')
print(f'Определитель:\n{np.linalg.det(a2):.0f}')

Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель:
-43


In [ ]:
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица:\n{a3}')
print(f'Определитель:\n{np.linalg.det(a3):.0f}')

Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель:
43


$$detA_{1}=86,$$

$$detA_{2}=-43,$$

$$detA_{3}=43,$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1.$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$