### Практическое задание Часть 3

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__ 

Произведение двух матриц определено лишь в случае, когда число
столбцов первого сомножителя равно числу строк второго.
Иными словами, если матрица A имеет размер k × x, а матрица B —
размер r × m, то произведение AB существует тогда и только тогда, когда
x = r .

а) AB и BA не определены;

б) AB - определено, размерность 2×3. BA не определено;

в) AB и BA определены. AB размерность 8×8. BA размерность 3×3;

г) AB и BA определены, размерности 4×4.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__ 

$A+B=B+A=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$AB=\begin{pmatrix}
1*4+-2*0 & 1*-1+-2*5\\ 
3*4+0*0 & 3*-1+0*5
\end{pmatrix}=
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

$BA=\begin{pmatrix}
4*1+-1*3 & 4*-2+-1*0\\ 
0*1+5*3 & 0*-2+5*0
\end{pmatrix}=
\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [2]:
# проверка
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A + B\n{A + B}\n')
print(f'Матрица A * B\n{np.dot(A, B)}\n')
print(f'Матрица B * A\n{np.dot(B, A)}')

Матрица A + B
[[ 5 -3]
 [ 3  5]]

Матрица A * B
[[  4 -11]
 [ 12  -3]]

Матрица B * A
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__

$3A-2B+4C = 3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [3]:
# проверка
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A−2B+4C = \n{3*A - 2*B + 4*C}\n')

3A−2B+4C = 
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__Решение__

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$


$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} * 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = 
\begin{pmatrix}
4*4+1*1 & 4*5+1*-2 & 4*2+1*3\\ 
5*4+-2*1 & 5*5+-2*-2 & 5*2+-2*3\\
2*4+3*1 & 2*5+3*-2 & 2*2+3*3
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} * 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = 
\begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*-2+2*3\\ 
1*4+-2*5+3*2 & 1*1+-2*-2+3*3
\end{pmatrix} = 
\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [4]:
# проверка
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'AAt = \n{np.dot(A, A.T)}\n')
print(f'AtA = \n{np.dot(A.T, A)}\n')

AAt = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

AtA = 
[[45  0]
 [ 0 14]]



### Практическое задание Часть 4

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__Решение__

a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx\cdot sinx - (-cosx) \cdot cosx = sin^2x + cos^2x = 1$

б)

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=
4\cdot\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix}=4\cdot(5\cdot9-1\cdot0)-2\cdot(0\cdot9-1\cdot0)+3\cdot(0\cdot0-5\cdot0)=180-0+0=180.
$

In [5]:
# проверка
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\cdot\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix}=1\cdot(5\cdot9-6\cdot8)-2\cdot(4\cdot9-6\cdot7)+3\cdot(4\cdot8-5\cdot7)=-3+12-9=0
$

In [6]:
# проверка
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__ 

а) 

Так как по свойству определителей для двух квадратных матриц одинакового размера 

$$det(AB)=detA\cdot detB$$

$det(A)=4$

то

$det(A^{2}) = det(A\cdot A) = det(A)\cdot det(A) = 4\cdot4 = 16$

б) 

Так как по свойству определителей определитель транспонированной матрицы равен определителю исходной

$$detA^{T}=detA.$$

$det(A)=4$

то

$det(A^{T}) = det(A) = 4$

в) 

Так как по свойству определителей умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число

$det(A)=4$

то

$det(2A) = 2\cdot det(A) = 8$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение__

Матрица называется вырожденной, если ее определитель равен 0.

По свойству определителей, если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

В данном случае первая и вторая строка линейно зависимы, так как вторая строка равна первой строке, умноженной на $-2$

In [7]:
# проверка
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Так как определитель равен нулю, значит матрица вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__

а)

$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$

И вычтем из второй строки первую:

$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}$$

Таким образом, ранг матрицы равен $2$.

In [8]:
# проверка
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


б)

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Переставим местами первую и третью строки:

$$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1
\end{pmatrix}$$


И вычтем из третьей строки вторую:

$$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1
\end{pmatrix}$$

Таким образом, ранг матрицы равен $3$.

In [9]:
# проверка
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
